### ISSUE TITLE
top_k_inc会报错

### ISSUE THREAD

**Issue by zoopigzoo** [lipiji/Guyu#1]
输入是三个不同的句子的时候：

`s = ["有一天", "早上好啊", "好累啊"]`

用

`top_k_inc(s)`

会报错：

![image](https://user-images.githubusercontent.com/4337354/80192037-2a61ab80-8649-11ea-8400-d4df28f49f02.png)

**Comment by zoopigzoo** [comment]
top_k不会，如果三个句子一个长度top_k_inc也不会

**Comment by lipiji** [comment]
对，这个是用来一个query生成多个结果的，所以s里面是单个query的复制。 当然用同样长度的不同query也行。
