### ISSUE TITLE
Is there any Problem  here?

### ISSUE THREAD

**Issue by huangdacheng** [lipiji/Guyu#14]
https://github.com/lipiji/Guyu/blob/18d79cd42eedf73041a4ec4c5ed7f8f6d7ddfcfd/transformer_preln.py#L56

Traceback (most recent call last):
  File "inference_dev.py", line 10, in <module>
    from inference import *
  File "../inference.py", line 9, in <module>
    from biglm import BIGLM
  File "../biglm.py", line 8, in <module>
    from transformer_preln import TransformerLayer, Embedding, LearnedPositionalEmbedding, SelfAttentionMask
  File "../transformer_preln.py", line 56
    = self.ff_layer_norm(x)
    ^
IndentationError: unexpected indent

**Comment by lipiji** [comment]
@huangdacheng  sorry for that, fixed.

**Comment by MianWang123** [comment]
![0](https://user-images.githubusercontent.com/57355956/159698539-fe5278fa-7a43-4fb9-bc22-4c89b20fdc02.png)
![1](https://user-images.githubusercontent.com/57355956/159698997-2a26bdfd-579d-411d-a2ec-86f3deb5a823.PNG)

How about this Error in inference.py? j is not an integer, has anyone met this problem?

**Comment by MianWang123** [comment]
> ![0](https://user-images.githubusercontent.com/57355956/159698539-fe5278fa-7a43-4fb9-bc22-4c89b20fdc02.png) ![1](https://user-images.githubusercontent.com/57355956/159698997-2a26bdfd-579d-411d-a2ec-86f3deb5a823.PNG)
> 
> How about this Error in inference.py? j is not an integer, has anyone met this problem?

Fixed! I should use floor divide here "idx_last_traces = idx_top_joint_scores // dict_size" to make sure it's integer.
