### ISSUE TITLE
可以提供国内的下载地址吗

### ISSUE THREAD

**Issue by ScottishFold007** [lipiji/Guyu#3]
您好！大牛！谷歌这个经常下载不全，能否提供一个国内网盘的下载链接？

**Comment by kifish** [comment]
其实从google drive下载的文件完整性是可以保证的，百度网盘则不能。有一些脚本是可以用过命令行来下载google drive里的文件的。如果可以解决网络的问题，可以试试这里的脚本https://github.com/imcaspar/gpt2-ml/tree/master/3rd/gdown.pl
