### ISSUE TITLE
可用huggingface的代码转为pytorch模型吗

### ISSUE THREAD

**Issue by wind91725** [lipiji/Guyu#4]

**Comment by songyouwei** [comment]
转不了的。我对比了一下，这里的TransformerLayer跟huggingface的GPT2的Block的参数量是一致的，不过实现的细节不一样，LayerNorm的位置不同，另外增加了几个Dropout。
```
huggingface gpt2:
	Block: LayerNorm*2 + Attention + MLP(Conv1D*2)
	forward: ln1 - attn - add - ln2 - mlp(fc1-act-fc2-drop) - add

biglm:
	TransformerLayer: LayerNorm*2 + Attention + Linear*2 + Dropout
	forward: attn - drop - add - ln1 - mlp(fc1-act-drop-fc2-drop) - add - ln2
```

**Comment by wind91725** [comment]
感谢回复 谢谢




在2020年05月29日 10:59，songyouwei 写道：

转不了的。我看了一下，这里的TransformerLayer跟huggingface的GPT2的Block的参数量是一致的，不过实现的细节不一样，LayerNorm的位置不同，另外增加了几个Dropout

**Comment by wind91725** [comment]
> 转不了的。我对比了一下，这里的TransformerLayer跟huggingface的GPT2的Block的参数量是一致的，不过实现的细节不一样，LayerNorm的位置不同，另外增加了几个Dropout。
> 
> ```
> huggingface gpt2:
> 	Block: LayerNorm*2 + Attention + MLP(Conv1D*2)
> 	forward: ln1 - attn - add - ln2 - mlp(fc1-act-fc2-drop) - add
> 
> biglm:
> 	TransformerLayer: LayerNorm*2 + Attention + Linear*2 + Dropout
> 	forward: attn - drop - add - ln1 - mlp(fc1-act-drop-fc2-drop) - add - ln2
> ```
兄嘚 现在有支持huggingface gpt2 调用的中文模型吗
